/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData attention = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_circled = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf002, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times = IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xf023, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xf029, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf049, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xf077, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xf078, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xf095, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_down = IconData(0xf0d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_up = IconData(0xf0d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_right = IconData(0xf0da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sitemap = IconData(0xf0e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel = IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tie = IconData(0xf508, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xf54e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restroom = IconData(0xf7bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xefaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
