const Map<String, Object> jsonContentTemplate = {
  "ActiveDate": "2019-06-22T02:45:12.7400004Z",
  "Code": "",
  "Description": "",
  "Discount": 10000,
  "DiscountRatio": 0,
  "DiscountToView": "10000.0",
  "DiscountValue": 10000,
  "ExcessCash": 0,
  "Id": 0,
  "MoreAttributes":
      "{\"PointDiscount\":0.0,\"PointDiscountValue\":0.0,\"Vouchers\":[]}",
  "NumberOfGuests": 1,
  "OfflineId": "d3a6432c-4b6e-4558-88fe-43d61a607570",
  "OldDebt": 0,
  "OrderDetails": [
    {
      "AttributesName": "",
      "BasePrice": 40000,
      "BlockOfTimeToUseService": 6,
      "BonusPoint": 0,
      "BonusPointForAssistant": 0,
      "BonusPointForAssistant2": 0,
      "BonusPointForAssistant3": 0,
      "CategoryId": 124195,
      "Checkin": "",
      "Checkout": "",
      "Code": "TG",
      "Code2": "",
      "Code3": "",
      "Code4": "",
      "Coefficient": 0,
      "ConversionValue": 24,
      "Description": "",
      "descriptionOff": "",
      "DiscountRatio": 0,
      "ProductId": 2170127,
      "IsCheckPriceServer": true,
      "Hidden": false,
      "IsLargeUnit": false,
      "IsPercentageOfTotalOrder": false,
      "IsPriceForBlock": false,
      "IsSerialNumberTracking": false,
      "isShowOtherDescription": false,
      "SplitForSalesOrder": true,
      "IsTimer": false,
      "isUpdateTimeCheckInOrCheckOut": false,
      "LabelPrinted": 0,
      "LargeUnit": "THÙNG",
      "LargeUnitCode": "",
      "Name": "Tiger",
      "OnHand": -2532.2,
      "OnlinePrice": 0,
      "OrderQuickNotes": "",
      "Price": 40000,
      "PriceConfig":
          "{\"Block\":0,\"CalcPriceToTime\":\"\",\"DontPrintLabel\":false,\"SecondPrinter\":\"\",\"TimeFrom\":\"\",\"TimeFrom2\":\"\",\"TimeTo\":\"\",\"TimeTo2\":\"\",\"TimeValue\":0,\"TimeValue2\":0,\"Type\":\"percent\",\"Type2\":\"percent\",\"Value\":0}",
      "PriceLargeUnit": 80000,
      "Printer": "KitchenD",
      "Processed": 0,
      "ProductImages": [],
      "ProductType": 1,
      "Quantity": 1,
      "Serveby": 0,
      "StopTimer": false,
      "sumSecondsNormal": 0,
      "TotalTopping": 0,
      "Unit": "Lon",
      "UnitPrice": 40000
    },
    {
      "AttributesName": "",
      "BasePrice": 45000,
      "BlockOfTimeToUseService": 6,
      "BonusPoint": 0,
      "BonusPointForAssistant": 0,
      "BonusPointForAssistant2": 0,
      "BonusPointForAssistant3": 0,
      "CategoryId": 124195,
      "Checkin": "",
      "Checkout": "",
      "Code": "HNK",
      "Code2": "",
      "Code3": "",
      "Code4": "",
      "Coefficient": 0,
      "ConversionValue": 24,
      "Description": "",
      "descriptionOff": "",
      "DiscountRatio": 0,
      "ProductId": 2170126,
      "IsCheckPriceServer": true,
      "Hidden": false,
      "IsLargeUnit": false,
      "IsPercentageOfTotalOrder": false,
      "IsPriceForBlock": false,
      "IsSerialNumberTracking": false,
      "isShowOtherDescription": false,
      "SplitForSalesOrder": false,
      "IsTimer": false,
      "isUpdateTimeCheckInOrCheckOut": false,
      "LabelPrinted": 0,
      "LargeUnit": "THÙNG",
      "LargeUnitCode": "",
      "Name": "Heinekenken",
      "OnHand": 121,
      "OnlinePrice": 0,
      "OrderQuickNotes": "bia cho mùa hè",
      "Price": 40500,
      "PriceConfig":
          "{\"Block\":0.0,\"CalcPriceToTime\":\"\",\"DontPrintLabel\":false,\"SecondPrinter\":\"\",\"TimeFrom\":\"\",\"TimeFrom2\":\"\",\"TimeTo\":\"\",\"TimeTo2\":\"\",\"TimeValue\":0.0,\"TimeValue2\":0.0,\"Type\":\"percent\",\"Type2\":\"percent\",\"Value\":0.0}",
      "PriceLargeUnit": 372000,
      "Printer": "KitchenA",
      "Processed": 0,
      "ProductImages": [],
      "ProductType": 1,
      "Quantity": 1,
      "Serveby": 0,
      "StopTimer": false,
      "sumSecondsNormal": 0,
      "TotalTopping": 0,
      "Unit": "Lon",
      "UnitPrice": 45000
    },
    {
      "AttributesName": "",
      "BasePrice": 40000,
      "BlockOfTimeToUseService": 6,
      "BonusPoint": 0,
      "BonusPointForAssistant": 0,
      "BonusPointForAssistant2": 0,
      "BonusPointForAssistant3": 0,
      "CategoryId": 124195,
      "Checkin": "",
      "Checkout": "",
      "Code": "SG",
      "Code2": "",
      "Code3": "",
      "Code4": "",
      "Coefficient": 0,
      "ConversionValue": 24,
      "Description": "",
      "descriptionOff": "",
      "DiscountRatio": 0,
      "ProductId": 2170125,
      "IsCheckPriceServer": true,
      "Hidden": false,
      "IsLargeUnit": false,
      "IsPercentageOfTotalOrder": false,
      "IsPriceForBlock": false,
      "IsSerialNumberTracking": false,
      "isShowOtherDescription": false,
      "SplitForSalesOrder": false,
      "IsTimer": false,
      "isUpdateTimeCheckInOrCheckOut": false,
      "LabelPrinted": 0,
      "LargeUnit": "THÙNG",
      "LargeUnitCode": "",
      "Name": "Saigon",
      "OnHand": -62809.2,
      "OnlinePrice": 0,
      "OrderQuickNotes": "",
      "Price": 36000,
      "PriceConfig":
          "{\"Block\":0.0,\"CalcPriceToTime\":\"\",\"DontPrintLabel\":false,\"SecondPrinter\":\"\",\"TimeFrom\":\"\",\"TimeFrom2\":\"\",\"TimeTo\":\"\",\"TimeTo2\":\"\",\"TimeValue\":0.0,\"TimeValue2\":0.0,\"Type\":\"percent\",\"Type\n2019-06-22 09:45:33.192 23465-23465/vn.pos365.cashierspos365 E/PrintServiceCompanion: 2\":\"percent\",\"Value\":0.0}",
      "PriceLargeUnit": 100000,
      "Printer": "KitchenA",
      "Processed": 0,
      "ProductImages": [],
      "ProductType": 1,
      "Quantity": 1,
      "Serveby": 0,
      "StopTimer": false,
      "sumSecondsNormal": 0,
      "TotalTopping": 0,
      "Unit": "Lon",
      "UnitPrice": 40000
    }
  ],
  "PointToValue": 1000,
  "Pos": "A",
  "PriceBookId": "3689",
  "PurchaseDate": "",
  "RoomId": 119877,
  "RoomName": "Bàn 2",
  "ShippingCost": "0.0",
  "ShippingCostForPartner": 0,
  "SoldById": 167053,
  "Status": 2,
  "Total": 112750,
  "TotalPayment": 112750,
  "VAT": 10250,
  "VATRates": "10",
  "Voucher": 0
};

const Map<String, Object> jsonProductTemplate = {
  "AttributesName": "",
  "BasePrice": 40000,
  "BlockOfTimeToUseService": 6,
  "BonusPoint": 0,
  "BonusPointForAssistant": 0,
  "BonusPointForAssistant2": 0,
  "BonusPointForAssistant3": 0,
  "CategoryId": 0,
  "Checkin": "",
  "Checkout": "",
  "Code": "HH-0001",
  "Code2": "",
  "Code3": "",
  "Code4": "",
  "Coefficient": 1,
  "ConversionValue": 1,
  "Description": """-Thạchnhađamx1=10,
000;-Trânchâuđenx1=5,
000;""",
  "Discount": 0,
  "DiscountRatio": 0,
  "Hidden": false,
  "Id": 17568254,
  "IsCheckPriceServer": true,
  "IsLargeUnit": false,
  "IsPercentageOfTotalOrder": false,
  "IsPriceForBlock": false,
  "IsSerialNumberTracking": false,
  "IsTimer": false,
  "LargeUnit": "",
  "Name": "Trà sữa hồng trà",
  "NameLatin": "tra sua hong tra",
  "OnHand": 0,
  "OnlinePrice": 0,
  "OrderQuickNotes": "",
  "Price": 55000,
  "PriceConfig":
      "{\"Type\":\"percent\",\"Type2\":\"percent\",\"DontPrintLabel\":false,\"OpenTopping\":false}",
  "PriceLargeUnit": 40000,
  "Printer": "KitchenA",
  "Processed": 0,
  "ProductId": 17568254,
  "ProductType": 1,
  "Quantity": 1,
  "Serveby": 0,
  "SplitForSalesOrder": false,
  "StopTimer": false,
  "Topping":
      "[{\"ExtraId\":17568257,\"QuantityExtra\":1,\"Price\":10000,\"Quantity\":1},{\"ExtraId\":17568255,\"QuantityExtra\":1,\"Price\":5000,\"Quantity\":1}]",
  "TotalTopping": 15000,
  "Unit": "",
  "UnitPrice": 40000,
  "index": 0,
  "LabelPrinted": 0
};

const Map<String, Object> jsonPartnerTemplate = {
  "Debt": 5000000.0000,
  "TotalTransactionvalue": 0.0000,
  "BranchId": 0,
  "Id": 6770182,
  "Code": "KH-10392",
  "Name": "Nguyễn Văn Nam",
  "Address": "230 Đống Đa",
  "Phone": "12356548",
  "Type": 1,
  "Gender": 0,
  "TotalDebt": 5295000.0000,
  "Loyalty": 0.0000,
  "CreatedBy": 0,
  "CreatedDate": "2022-08-22T06:29:04.6730000Z",
  "ModifiedDate": "2022-08-25T03:00:44.3270000Z",
  "RetailerId": 0,
  "Province": "DNG",
  "Point": 0,
  "ShippingAddress": "230 Đống Đa",
  "Phone2": "6161651",
  "Transactionvalue": 0.0000,
  "PartnerGroupMembers": []
};

const Map<String, Object> jsonVoucherTemplate = {
  "Id": 172456,
  "Code": "PTKL131198",
  "Value": 10.0000,
  "RetailerId": 375,
  "CreatedDate": "2022-09-13T08:29:56.2770000Z",
  "CreatedBy": 167053,
  "IsPercent": true,
  "Quantity": 1
};
