const String $appName = 'EMO';

const $phoneSupport = '097123123';

class AppConstant {
  AppConstant._();

  static const Map<int, String> mapBankBIN = {
    970400: "(SAIGONBANK) Ngân hàng TMCP Sài Gòn Công Thương",
    970403: "(SACOMBANK) Ngân hàng TMCP Sài Gòn Thương Tín",
    970405: "(AGRIBANK) Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
    970406: "(DONG A BANK) Ngân hàng TMCP Đông Á",
    970407: "(TECHCOMBANK) Ngân hàng TMCP Kỹ Thương Việt Nam",
    970408: "(GP Bank) Ngân hàng TNHH Một Thành Viên Dầu Khí Toàn Cầu",
    970409: "(BAC A BANK) Ngân hàng TMCP Bắc Á",
    970410: "(Standard Chartered) Ngân hàng TNHH Một Thành Viên Standard Chartered",
    970412: "(PVcomBank) Ngân hàng TMCP Đại Chúng Việt Nam",
    970414: "(OceanBank) Ngân hàng TNHH Một Thành Viên Đại Dương",
    970415: "(VietinBank) Ngân hàng TMCP Công Thương Việt Nam",
    970416: "(ACB) Ngân hàng TMCP Á Châu",
    970418: "(BIDV) Ngân hàng Đầu tư và Phát triển Việt Nam",
    970419: "(NCB) Ngân hàng TMCP Quốc Dân",
    970421: "(VRB) Ngân hàng Liên doanh Việt Nga",
    970422: "(MB BANK) Ngân hàng TMCP Quân Đội",
    970423: "(TPBank) Ngân hàng TMCP Tiên Phong",
    970424: "(Shinhan Bank) Ngân hàng TNHH Một Thành Viên Shinhan Việt Nam",
    970425: "(ABBANK) Ngân hàng TMCP An Bình",
    970426: "(MSB) Ngân hàng TMCP Hàng Hải",
    970427: "(VietABank) Ngân hàng TMCP Việt Á",
    970428: "(Nam A Bank) Ngân hàng TMCP Nam Á",
    970429: "(SCB) Ngân hàng TMCP Sài Gòn",
    970430: "(PG Bank) Ngân hàng TMCP Xăng dầu Petrolimex",
    970431: "(Eximbank) Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
    970432: "(VPBank) Ngân hàng TMCP Việt Nam Thịnh Vượng",
    970433: "(VietBank) Ngân hàng TMCP Việt Nam Thương Tín",
    970434: "(Indovina) Ngân hàng TNHH Indovina",
    970436: "(Vietcombank) Ngân hàng TMCP Ngoại thương Việt Nam",
    970437: "(HDBank) Ngân hàng TMCP Phát triển TP.HCM",
    970438: "(BaoVietBank) Ngân hàng TMCP Bảo Việt",
    970439: "(PublicBank) Ngân hàng TNHH Một Thành Viên Public Việt Nam",
    970440: "(SeABank) Ngân hàng TMCP Đông Nam Á",
    970441: "(VIB) Ngân hàng TMCP Quốc Tế Việt Nam",
    970442: "(Hong Leong) Ngân hàng TNHH Một Thành Viên Hong Leong Việt Nam",
    970443: "(SHB) Ngân hàng TMCP Sài Gòn – Hà Nội",
    970444: "(CBBank) Ngân hàng TNHH Một Thành Viên Xây Dựng Việt Nam",
    970446: "(Co-opBank) Ngân hàng Hợp Tác Xã Việt Nam",
    970448: "(OCB) Ngân hàng TMCP Phương Đông",
    970449: "(LPBank) Ngân hàng TMCP Bưu Điện Liên Việt",
    970452: "(KienLongBank) Ngân hàng TMCP Kiên Long",
    970454: "(Viet Capital Bank) Ngân hàng TMCP Bản Việt",
    970455: "(IBK Hanoi Branch) Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội",
    970456: "(Industrial Bank of Korea) Ngân hàng Industrial Bank of Korea - Chi nhánh Hồ Chí Minh",
    970457: "(Woori Bank) Ngân hàng TNHH Một Thành Viên Woori Bank Việt Nam",
    970458: "(United Overseas Bank) Ngân hàng TNHH Một Thành Viên UOB Việt Nam",
    970459: "(CIMB) Ngân hàng TNHH Một Thành Viên CIMB Việt Nam",
    970460: "(CFC) Công ty Tài chính cổ phần Xi Măng",
    970462: "(Kookmin Hà Nội) Ngân hàng Kookmin - Chi nhánh Hà Nội",
    970463: "(Kookmin Hồ Chí Minh) Ngân hàng Kookmin - Chi nhánh Tp. Hồ Chí Minh",
    970464: "(TFC) Công ty Tài chính TNHH MTV CỘNG ĐỒNG",
    970465: "(SINOPAC) Ngân hàng SINOPAC - Chi nhánh Tp. Hồ Chí Minh",
    970466: "(KEB HANA Hồ Chí Minh) Ngân hàng KEB HANA - Chi nhánh Tp. Hồ Chí Minh",
    970467: "(KEB HANA Hà Nội) Ngân hàng KEB HANA - Chi nhánh Hà Nội",
    970468: "(Mirae Asset) Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)",
    970469: "(EVF) Công ty Cổ phần Tài chính Điện lực",
    970470: "(Mcredit) Công ty Tài chính TNHH MB SHINSEI"
  };
}
